//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate not Exist.
        /// </summary>
        internal static string BirthDTntExst {
            get {
                return ResourceManager.GetString("BirthDTntExst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangeEffectiveDate not Exist.
        /// </summary>
        internal static string ChangeEfftDatentExt {
            get {
                return ResourceManager.GetString("ChangeEfftDatentExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COI not Exist.
        /// </summary>
        internal static string COInotExs {
            get {
                return ResourceManager.GetString("COInotExs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        internal static string DateFormat_ddMMyyyy {
            get {
                return ResourceManager.GetString("DateFormat_ddMMyyyy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddMMyyyy_HHmmss.
        /// </summary>
        internal static string DateFormat_ddMMyyyy_HHmmss {
            get {
                return ResourceManager.GetString("DateFormat_ddMMyyyy_HHmmss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/dd/yyyy.
        /// </summary>
        internal static string DateFormat_MMddyyyy {
            get {
                return ResourceManager.GetString("DateFormat_MMddyyyy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateofIntimation not Exist.
        /// </summary>
        internal static string DtofIntimationnotExs {
            get {
                return ResourceManager.GetString("DtofIntimationnotExs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmploymentDate not Exist.
        /// </summary>
        internal static string EmpDtntExst {
            get {
                return ResourceManager.GetString("EmpDtntExst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeNo not Exist.
        /// </summary>
        internal static string EmpNontExs {
            get {
                return ResourceManager.GetString("EmpNontExs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSG is not exist.
        /// </summary>
        internal static string FSGExst {
            get {
                return ResourceManager.GetString("FSGExst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender not Exist.
        /// </summary>
        internal static string GenderntExst {
            get {
                return ResourceManager.GetString("GenderntExst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload status: The file has to be less than 3 MB.
        /// </summary>
        internal static string lessthan100 {
            get {
                return ResourceManager.GetString("lessthan100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not uploaded..
        /// </summary>
        internal static string msgErrNoFile {
            get {
                return ResourceManager.GetString("msgErrNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Record Found.
        /// </summary>
        internal static string MsgRecordNotFound {
            get {
                return ResourceManager.GetString("MsgRecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload status: The file could not be uploaded.
        /// </summary>
        internal static string NotSuccessfulFileUpload {
            get {
                return ResourceManager.GetString("NotSuccessfulFileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProposedFirstName not Exist.
        /// </summary>
        internal static string PropFirstNamenotExst {
            get {
                return ResourceManager.GetString("PropFirstNamenotExst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Saved Successfully.
        /// </summary>
        internal static string RecordSavedSucessfully {
            get {
                return ResourceManager.GetString("RecordSavedSucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SchemeJoiningDate not Exist.
        /// </summary>
        internal static string SchemeJoiningDtNE {
            get {
                return ResourceManager.GetString("SchemeJoiningDtNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubofficeCode not Exist.
        /// </summary>
        internal static string subOffnotEx {
            get {
                return ResourceManager.GetString("subOffnotEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload status: File uploaded!.
        /// </summary>
        internal static string successfulFileUplod {
            get {
                return ResourceManager.GetString("successfulFileUplod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminationdt not Exist.
        /// </summary>
        internal static string TermdtntExst {
            get {
                return ResourceManager.GetString("TermdtntExst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message.
        /// </summary>
        internal static string WebResource {
            get {
                return ResourceManager.GetString("WebResource", resourceCulture);
            }
        }
    }
}
